distributed:
  addr: ""
  bootstrap_node: ""
  batch_period: 15000
  checkkeys_period: 30000
  dht:
    vnode_num: 16
    succlist_length: 2
    stabilize_interval: 15000
    fixfingers_interval: 10000

politeness:
  max_active_queues: 512
  multiplier: 5
  session_budget: 5
  timeout: 3000

seed: seed.txt
